import { Html, Head, Main, NextScript } from 'next/document'
import { BsFillBrushFill, BsChatDotsFill } from 'react-icons/bs'
import { GiWhaleTail } from 'react-icons/gi'
import Link from 'next/link'

export default function Document() {
    return (
        <Html>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
            </Head>
            <body>
                <nav className="w-100 text-white py-3 px-4 d-flex justify-content-between align-items-center" style={{ background: '#141b25' }}>
                    <Link href="/">
                        <a className='d-flex align-items-center gap-2'>
                            <GiWhaleTail fontSize="2rem" />
                            <span>Business-arch</span>
                        </a>
                    </Link>
                    <div className='d-flex gap-4'>
                        <Link href="/NewPage">
                            <a className='d-flex gap-2 align-items-center'>
                                <BsFillBrushFill />
                                <span>新增紀錄</span>
                            </a>
                        </Link>
                        <Link href="/FileRecord">
                            <a className='d-flex gap-2 align-items-center'>
                                <BsChatDotsFill />
                                <span>存檔紀錄</span>
                            </a>
                        </Link>
                    </div>
                </nav>
                <Main />
                <NextScript />
                <div id='modal' />
            </body>
        </Html>
    )
}