import { Html, Head, Main, NextScript } from 'next/document'
import Link from 'next/link'
import { BsFillBrushFill,BsChatDotsFill } from 'react-icons/bs'

export default function Document() {
    return (
        <Html>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
            </Head>
            <body>
                <nav className="w-100 py-3 px-4 d-flex gap-4 justify-content-end" style={{ background: '#141b25' }}>
                    <Link href="/NewPage">
                        <a className='text-white d-flex gap-2 align-items-center'>
                            <BsFillBrushFill/>
                            <span>新增紀錄</span>
                        </a>
                    </Link>
                    <Link href="/FileRecord">
                        <a className='text-white d-flex gap-2 align-items-center'>
                            <BsChatDotsFill/>
                            <span>存檔紀錄</span>
                        </a>
                    </Link>
                </nav>
                <Main />
                <NextScript />
            </body>
        </Html>
    )
}