import Head from 'next/head'
import TreeView from '../components/TreeView'
import Data from '../public/Data.json'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Business Architecture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='MainPanel'>
        <ul>
          <TreeView data={Data} />
        </ul>
      </div>
    </div>
  )
}
