import Head from 'next/head'
import TreeView from './components/TreeView'
const data = {
  body: "社會",
  content: [
    {
      body: "低端社會",
      content: [
        {
          body: "社會畜牲",
          content: [
            {
              body: "專案經理",
              content: [
                {
                  body: "PM",
                  content: []
                },
                {
                  body: "RD",
                  content: []
                }
              ]
            },
            {
              body: "系統分析",
              content: [],
            },
            {
              body: "開發工程師",
              content: [],
            }
          ]
        },
        {
          body: "社會蟑螂",
          content: []
        },
        {
          body: "社會米蟲",
          content: []
        }
      ]
    },
    {
      body: "高端社會",
      content: []
    }
  ]
}
export default function Home() {
  return (
    <div>
      <Head>
        <title>Business Architecture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='MainPanel'>
        <ul>
          <TreeView data={data} />
        </ul>
      </div>
    </div>
  )
}
