import Head from 'next/head'
import TreeView from './components/TreeView'
const data = {
  body: "社會",
  content: [
    {
      body: "低端社會",
      content: [
        {
          body: "社會畜牲",
          content: [
            {
              body: "加班牛",
              content: [
                {
                  body: "做到死了",
                  content: []
                },
                {
                  body: "死了都要做",
                  content: []
                }
              ]
            },
            {
              body: "失業豬",
              content: [],
            },
            {
              body: "壓榨雞",
              content: [],
            }
          ]
        },
        {
          body: "社會蟑螂",
          content: []
        },
        {
          body: "社會米蟲",
          content: []
        }
      ]
    },
    {
      body: "高端社會",
      content: [
        {
          body: "社會雲端",
          content: []
        },
        {
          body: "金字塔頂端",
          content: []
        }
      ]
    }
  ]
}
export default function Home() {
  return (
    <div>
      <Head>
        <title>Business Architecture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='MainPanel'>
        <ul>
          <TreeView data={data} />
        </ul>
      </div>
    </div>
  )
}
